
TRANSCRIPT_ID = "Transcript ID"
GENE_ID = "Gene ID"
GENE_NAME = "Gene name"
CHROMOSOME = "Chromosome"
STRAND = "Strand"
TRANSCRIPT_START = "Transcript genomic start position"
EXON_POSITIONS = "Exon positions"
FEATURE_REGION = "Feature region"
N_FEATURES_IN_TRANSCRIPT = "N instances of feature within transcript"
FEATURE_NUMBER = "Feature number within transcript"
JUNCTION_DEFINITION = "Junction loci"
ALL_JUNCTIONS = "All splice junctions"
OVERLAPPING_JUNCTIONS = "Overlapping splice junctions"
AVG_NUMBER = "Avg N events"
AVG_FREQUENCY = "Avg percent detection"
